### ISSUE TITLE
Plugin doesn't send messages anymore

### ISSUE THREAD

**Issue by joseluisq** [mike1pol/drone-rocket#2]
This plugin is not sending messages anymore because `Content-type: application/json` missing header during client request.

https://github.com/mike1pol/drone-rocket/blob/7cc780ad8df0fbf2429e5a7e4a8d64aa41a1a141/plugin.go#L151-L157

Also `err` check should be before the `defer`.

BTW I did a fork at https://github.com/joseluisq/drone-rocketchat because I wanted that fix ASAP. However since I don't intend to support it so It would be great if you can address this issue in order to be able to continue using this plugin.
Or let me know if you are interested in a PR for that particular fix.

**Comment by mike1pol** [comment]
PR Welcome

**Comment by joseluisq** [comment]
Thanks for the invitation. A PR should come in coming hours.
